-- 011_personal_life_seed.sql · R51-γ · 2026-05-28
--
-- Seeds Marat's life-domain hierarchy as PRE-ACCEPTED synthetic_domains in
-- the mbp-private workspace. These are NOT generated by the detector — they
-- are operator-authored ground-truth roots that the detector treats as the
-- baseline against which it proposes new cross-cutting domains.
--
-- Six initial domains per the plan §"PHASE 2 / Wave γ":
--   Health, Finance, Family, Work, Learning, Creative
--
-- Each domain has:
--   * workspace_id = 'mbp-private'  (operator-only ecosystem)
--   * owner_user_id = 'marat'
--   * visibility = 'operator_only'
--   * status = 'active'
--   * binding = empty selector {version:1, combine:any, filters:[]}
--     (operator binds projects via UI; until bound, membership is empty)
--   * metadata.seed_source = 'r51_gamma_personal_life_seed'
--   * metadata.is_pre_accepted_root = true (detector excludes from candidate
--     emission; treats as fixed baseline)
--
-- Idempotent: ON CONFLICT (workspace_id+slug uniqueness) DO NOTHING.
--
-- Why pre-accepted roots and not detector emissions:
--   The 14-signal taxonomy needs SOMETHING to cross-reference against. With
--   zero existing domains the detector has no DDC ≥ 2 candidate set. Seeding
--   the canonical six life domains gives the detector a basis to propose
--   cross-cutting *between* them (e.g. "Health × Finance × Family =
--   personal_life_ikigai_candidate" per §16.4.1 example).

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM workers_schema_version WHERE version = 11) THEN

    -- Insert each life-domain root. We use deterministic IDs so the seed is
    -- idempotent and re-running produces no duplicates (the unique index
    -- on (workspace_id, slug) also enforces this).
    INSERT INTO synthetic_domains (
      id, workspace_id, slug, label, description,
      owner_user_id, visibility, edit_role, binding, binding_version,
      status, has_roadmap, goal_count, open_recommendation_count,
      metadata, created_at, updated_at
    ) VALUES
      (
        'sd_seed_mbp_health',  'mbp-private', 'health',   'Health',
        'Physical health, mental health, training, nutrition, sleep — operator-owned baseline life domain.',
        'marat', 'operator_only', 'owner',
        '{"version":1,"combine":"any","filters":[]}'::jsonb, 1,
        'active', false, 0, 0,
        '{"seed_source":"r51_gamma_personal_life_seed","is_pre_accepted_root":true,"life_domain":"health"}'::jsonb,
        now(), now()
      ),
      (
        'sd_seed_mbp_finance', 'mbp-private', 'finance',  'Finance',
        'Cashflow, taxes, investments, runway, household accounting — operator-owned baseline life domain.',
        'marat', 'operator_only', 'owner',
        '{"version":1,"combine":"any","filters":[]}'::jsonb, 1,
        'active', false, 0, 0,
        '{"seed_source":"r51_gamma_personal_life_seed","is_pre_accepted_root":true,"life_domain":"finance"}'::jsonb,
        now(), now()
      ),
      (
        'sd_seed_mbp_family',  'mbp-private', 'family',   'Family',
        'Family logistics, relationships, milestones, traditions — operator-owned baseline life domain.',
        'marat', 'operator_only', 'owner',
        '{"version":1,"combine":"any","filters":[]}'::jsonb, 1,
        'active', false, 0, 0,
        '{"seed_source":"r51_gamma_personal_life_seed","is_pre_accepted_root":true,"life_domain":"family"}'::jsonb,
        now(), now()
      ),
      (
        'sd_seed_mbp_work',    'mbp-private', 'work',     'Work',
        'Company building, MB-P/XCP/Xlooop platform work, commercial pursuit — operator-owned baseline life domain.',
        'marat', 'operator_only', 'owner',
        '{"version":1,"combine":"any","filters":[]}'::jsonb, 1,
        'active', false, 0, 0,
        '{"seed_source":"r51_gamma_personal_life_seed","is_pre_accepted_root":true,"life_domain":"work"}'::jsonb,
        now(), now()
      ),
      (
        'sd_seed_mbp_learning','mbp-private', 'learning', 'Learning',
        'Books, courses, deep-dives, language acquisition, skill experiments — operator-owned baseline life domain.',
        'marat', 'operator_only', 'owner',
        '{"version":1,"combine":"any","filters":[]}'::jsonb, 1,
        'active', false, 0, 0,
        '{"seed_source":"r51_gamma_personal_life_seed","is_pre_accepted_root":true,"life_domain":"learning"}'::jsonb,
        now(), now()
      ),
      (
        'sd_seed_mbp_creative','mbp-private', 'creative', 'Creative',
        'Creative pursuits — writing, music, image-making, hobby builds, side experiments — operator-owned baseline life domain.',
        'marat', 'operator_only', 'owner',
        '{"version":1,"combine":"any","filters":[]}'::jsonb, 1,
        'active', false, 0, 0,
        '{"seed_source":"r51_gamma_personal_life_seed","is_pre_accepted_root":true,"life_domain":"creative"}'::jsonb,
        now(), now()
      )
    ON CONFLICT (id) DO NOTHING;

    INSERT INTO workers_schema_version (version, description, applied_at)
    VALUES (11, 'R51-γ personal-life seed (6 pre-accepted root domains for mbp-private)', now());
  END IF;
END $$;

COMMIT;
