// security-headers.ts · defense-in-depth response headers for the API worker.
// X-SCP P0.1 — ingress plane (security control-plane plan §II.6).
//
// The worker serves JSON only (api.xlooop.com), so its document policy is locked
// down hard: a sniffed or reflected API response must be unable to execute script
// or be framed. The *app* CSP (the real XSS surface, app.xlooop.com) is set on the
// Cloudflare Pages `_headers` file generated by scripts/prepare-cloudflare-pages.mjs.
//
// Mirrors the cors.ts middleware shape (mutate ctx.res.headers after next()) rather
// than hono/secure-headers, matching the house pattern and avoiding clobbering
// headers a route set deliberately.

import { MiddlewareHandler } from 'hono';

const API_SECURITY_HEADERS: Record<string, string> = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'no-referrer',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Cross-Origin-Resource-Policy': 'same-origin',
  // JSON API · never a document → maximally strict CSP.
  'Content-Security-Policy': "default-src 'none'; frame-ancestors 'none'; base-uri 'none'",
};

export function securityHeaders(): MiddlewareHandler {
  return async (ctx, next) => {
    await next();
    for (const [name, value] of Object.entries(API_SECURITY_HEADERS)) {
      // Don't overwrite a header a route set on purpose.
      if (!ctx.res.headers.has(name)) ctx.res.headers.set(name, value);
    }
  };
}
